title: 'The 51st Class of Thomas J. Watson Fellows'
description: 'The 51st class came from 6 countries, 18 states, and traveled to 82 countries. These are their journeys.'
img: '/images/social-card.jpg'

sass:
  style: compressed
  load_paths:
    - _sass

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - bin
  - vendor

collections:
  fellows:
    output: true
    sort_by: title

plugins:
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      image: /images/social-card.png