title: Watson Foundation Fellows
description: 

sass:
  load_paths:
    - _sass

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - bin
  - vendor

collections:
  fellows:
    output: true
    sort_by: title