title: 'The 51st Class of Thomas J. Watson Fellows'
description: 

sass:
  style: compressed
  load_paths:
    - _sass

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - bin
  - vendor

collections:
  fellows:
    output: true
    sort_by: title